# Generated by Django 4.1.3 on 2023-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dateofbirth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('accounttype', models.CharField(max_length=300)),
                ('materials', models.CharField(max_length=500)),
            ],
        ),
    ]
