# Generated by Django 4.1.3 on 2023-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_mailid_form_email_rename_name_form_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
