# Generated by Django 4.1.3 on 2023-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_form_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
