# Generated by Django 4.1.3 on 2023-02-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_form_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='materials',
            field=models.CharField(max_length=50),
        ),
    ]
