# Generated by Django 4.1.3 on 2023-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_form_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
