# Generated by Django 4.1.3 on 2023-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
